const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {spawn}=require('child_process');
const path=require('path');
const root=path.resolve(__dirname,'..');
const servers=[spawn('python3',[path.join(root,'server/app.py')],{env:{...process.env,DEMO_MODE:'true',DATABASE_PATH:path.join(require('os').tmpdir(),'ir-ui-'+Date.now()+'.db')}}),spawn('python3',['-m','http.server','8081','--directory',path.join(root,'mobile/dist')])];
(async()=>{
 await new Promise(r=>setTimeout(r,1000));
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const out=path.join(root,'docs/screenshots/');
 await page.goto('http://localhost:8081');
 await page.getByRole('button',{name:'Start my free interview'}).waitFor();
 await page.screenshot({path:out+'01-onboarding.png',fullPage:true});
 await page.getByRole('button',{name:'Start my free interview'}).click();
 await page.getByLabel('Email address',{exact:true}).fill('qa'+Date.now()+'@example.com');
 await page.getByLabel('Password',{exact:true}).fill('StrongPassword123');
 await page.getByRole('checkbox').click();
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('button',{name:'Start an interview'}).waitFor();
 await page.screenshot({path:out+'02-home.png',fullPage:true});
 await page.getByRole('button',{name:'Start an interview'}).click();
 await page.getByLabel('Job description',{exact:true}).fill('Maintain CRM records, qualify leads and meet monthly sales targets.');
 await page.getByRole('button',{name:'Begin interview'}).click();
 await page.getByLabel('Your answer',{exact:true}).waitFor();
 await page.screenshot({path:out+'03-interview.png',fullPage:true});
 await page.getByLabel('Your answer',{exact:true}).fill('I have worked in sales and helped customers understand their options.');
 await page.getByRole('button',{name:'Save answer & continue',exact:true}).click();
 await page.getByRole('button',{name:'Continue without adding detail'}).click();
 await page.getByText('Question 2 of 5',{exact:true}).waitFor();
 await page.getByLabel('Your answer',{exact:true}).fill('A saved draft to verify interrupted practice.');
 await page.getByText('Draft saved',{exact:true}).waitFor();
 await page.reload();
 await page.getByRole('button',{name:'Resume interview'}).click();
 await page.getByLabel('Your answer',{exact:true}).waitFor();
 if(await page.getByLabel('Your answer',{exact:true}).inputValue()!=='A saved draft to verify interrupted practice.')throw new Error('Draft not restored');
 const answer='In my previous role I listened carefully to a customer who was unsure about the available options. I asked questions to understand their needs, explained the relevant choices clearly, and arranged a follow-up conversation. This helped us agree on the next step.';
 for(let i=1;i<5;i++){
   await page.getByLabel('Your answer',{exact:true}).fill(answer+' Example '+i+'.');
   await page.getByRole('button',{name:i===4?'Finish & see feedback':'Save answer & continue',exact:true}).click();
   if(i<4)await page.getByText(`Question ${i+2} of 5`,{exact:true}).waitFor();
 }
 await page.getByText('Progress starts here.',{exact:true}).waitFor();
 await page.screenshot({path:out+'04-feedback.png',fullPage:true});
 await page.getByRole('button',{name:'Practise this answer again'}).click();
 await page.getByLabel('Your answer',{exact:true}).fill(answer+' I confirmed the agreed next step by email.');
 await page.getByRole('button',{name:'Finish & see feedback',exact:true}).click();
 await page.getByText('Attempt 2',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'History'}).click();
 await page.getByRole('button',{name:'View feedback'}).waitFor();
 await page.screenshot({path:out+'05-history.png',fullPage:true});
 await page.getByRole('tab',{name:'Plans'}).click();
 await page.screenshot({path:out+'06-plans.png',fullPage:true});
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('PASS: sign-up, JD setup, 5 answers, follow-up, reload/resume, feedback, retry comparison, history, plans; no browser runtime errors.');
 await browser.close();servers.forEach(s=>s.kill());
})().catch(e=>{console.error(e);servers.forEach(s=>s.kill());process.exit(1)});
